=== aurelien-V03/trajectoires/src/xml/Trajectoire.xsd
<?xml version="1.0"?>


<xs:schema version="1.0"
           targetNamespace="http://www.univ-grenoble-alpes.fr/trajectoires"
           xmlns:pos="http://www.univ-grenoble-alpes.fr/trajectoires"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="Trajectoire" type="pos:Pos"/>
    
    <xs:complexType name="Trajectoire">
        <xs:sequence>
           <xs:element name="pos" type="pos:Coord"/>
        </xs:sequence>
    </xs:complexType>
    
     <xs:complexType name="Coord">
        <xs:sequence>
            <xs:element name="x" type="xs:double"/>
            <xs:element name="y" type="xs:double"/>
            <xs:element name="z" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== aurelien-V03/trajectoires/src/xml/trajectoires.xml
<?xml version="1.0" encoding="UTF-8"?>
<tr:Trajectoire
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:tr='http://www.univ-grenoble-alpes.fr/trajectoires'
    xsi:schemaLocation='http://www.univ-grenoble-alpes.fr/trajectoires Trajectoire.xsd'>
    <tr:pos>
        <tr:x>3</tr:x>
        <tr:y>1</tr:y>
        <tr:z>0</tr:z>
    </tr:pos>
    <tr:pos>
        <tr:x>4</tr:x>
        <tr:y>2</tr:y>
        <tr:z>0</tr:z>
    </tr:pos>
    <tr:pos>
        <tr:x>4</tr:x>
        <tr:y>2</tr:y>
        <tr:z>-1</tr:z>
    </tr:pos>
</tr:Trajectoire>
